### ISSUE TITLE
Initial Setup doesn't check if usernames are valid

### ISSUE THREAD

**Issue by isantop** [pop-os/gnome-initial-setup#10]
_From @Hronom on October 30, 2017 19:46_

Hello, on the initial setup screen, when you enter username that used for user home directory threre is no check is all charas are lowercased. This allow you to enter name `Hronom` that not allowed by the system, the correct is `hronom`. This bug don't allow user to continue use Pop OS because initial setup closes without errors and don't initialize reboot  of the system with compeltition of setup.

_Copied from original issue: pop-os/iso#191_

**Comment by brs17** [comment]
There are now checks to prevent such usernames.
