### ISSUE TITLE
Able to create invalid usernames

### ISSUE THREAD

**Issue by isantop** [pop-os/gnome-initial-setup#11]
_From @brs17 on October 11, 2017 21:46_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
The installer allows for the username of '..' to be created. No errors appear. Obviously though, the installation hangs as a home directory cannot be named '..'.

**Expected behaviour**
Error message should appear for such a username selection. 

_Copied from original issue: pop-os/iso#147_

**Comment by brs17** [comment]
There are now checks to prevent such usernames.
