### ISSUE TITLE
GNOME Initial Setup > Privacy > Location Services choice is not adhered to when enabled

### ISSUE THREAD

**Issue by isantop** [pop-os/gnome-initial-setup#15]
_From @WatchMkr on June 28, 2017 23:6_

**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
Pop!_OS 17.04 Alpha
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
gnome-initial-setup
```

**Actual issue**

Privacy > Location Services choice is not adhered to when enabled.

**Steps to reproduce (if you knew)**

Set Location Services to Enabled during GNOME Initial Setup. Login and observe the location setting in the System Menu.

**Expected behaviour**

Location Services setting is retained in the user account.

**Other Note (feature-request, question, etc...)**

_Copied from original issue: pop-os/iso#15_

**Comment by isantop** [comment]
_From @sarahpandabeara on October 4, 2017 18:33_

@WatchMkr is this related or different to the bug we encountered with location services not accurately capturing a location or allowing you to select "next"?

**Comment by isantop** [comment]
_From @WatchMkr on October 4, 2017 21:52_

this is different

**Comment by isantop** [comment]
_From @WatchMkr on October 6, 2017 12:43_

@sarahpandabeara This needs to be re-tested with Pop!_OS 17.10. I think this bug is fixed already.

**Comment by brs17** [comment]
Location services seem to be working as intended now.
