### ISSUE TITLE
GNOME initial Setup does not save user configuration

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gnome-initial-setup#17]
Retrieved laptop (leum8) went though the Setup and rebooted back into the GNOME Initial Setup user and the window to make the new user pops back up. Reinstalled today with a fresh image and it happens in that one as well.

**Comment by ahoneybun** [comment]
Not sure if it's the same person but another person posted on our reddit:
https://www.reddit.com/r/pop_os/comments/7cela8/gnomeinitialsetup_on_every_startup_problem/

**Comment by jackpot51** [comment]
What username have you been choosing?

**Comment by ahoneybun** [comment]
I'll ask on the reddit post.

**Comment by ahoneybun** [comment]
Seems someone found a workaround.

https://www.reddit.com/r/pop_os/comments/77kiu9/unable_to_complete_initial_setup/

**Comment by brs17** [comment]
So it seems that users have been getting this issue when selecting a username that is different than their selected name. Will investigate when I can.

**Comment by ahoneybun** [comment]
This customer was using uppercase in the username and the Setup was going though over and over till he changed it to lowercase 

https://system76.com/admin/support/view/25724

**Comment by ahoneybun** [comment]
This can also happen if they user selects to encrypt their drive as well. I've had two calls about it and that fixed the issue.
