### ISSUE TITLE
Don't ask about home encryption

### ISSUE THREAD

**Issue by jbicha** [pop-os/gnome-initial-setup#22]
Initial Setup in Pop!_OS 18.04 probably shouldn't ask about home encryption now that disk encryption is recommended in the installer.

As I discussed with jackpot51 earlier, Ubuntu 18.04 has dropped the home encryption question from its default installer. See https://launchpad.net/bugs/1756840

**Comment by jackpot51** [comment]
We will drop this once our production line installs recovery images that allow laptops to be reinstalled with full disk encryption out of the box

**Comment by brs17** [comment]
Home folder encryption is no longer an option in our gnome-initial-setup.
