### ISSUE TITLE
Gnome-initial-setup fails to complete

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#28]
**Distribution (run `cat /etc/os-release`):**
 18.10 debug 8
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-initial-setup

**Issue/Bug Description:**
After completing gnome-initial-setup, the newly created user is automatically logged in and gnome-initial-setup reappears.

journald outputs:

```
gnome-initial-s[2315]: Unable to retrieve object 'language_chooser' from class template for type 'GisLanguagePage' while building a 'GisLanguagePage'
gnome-initial-s[2315]: invalid (NULL) pointer instance
gnome-initial-s[2315]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
gnome-initial-s[2315]: invalid (NULL) pointer instance
gnome-initial-s[2315]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
followed by hundreds of the following line:
```
g_bytes_get_size: assertion 'bytes != NULL' failed
```

**Comment by jackpot51** [comment]
@brs17 a new version of gnome-initial-setup should be available after the next repos build, from the `master` staging repository

**Comment by brs17** [comment]
Debug iso 12 still has the same issue.

**Comment by brs17** [comment]
Just did another install with iso 12 and after completing gnome-initial-setup was just shown a blinking cursor on a black screen. Upon a reboot I was able to login successfully (but still was prompted with gnome-initial-setup)

**Comment by jackpot51** [comment]
Fixed via gdm patches
