### ISSUE TITLE
gnome-initial-setup does not launch centered on the screen

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#29]
When gnome-initial-setup executes, the program does not start in the middle of the screen but rather to the left side.

**Comment by mmstick** [comment]
I wonder if we should add a `g_idle_add()` that checks the screen height and modifies the window automatically as the screen size changes, rather than depending on the one initial check at startup.

**Comment by brs17** [comment]
Looks like this issue does not currently effect hidpi displays.

**Comment by brs17** [comment]
@mmstick he removed the check to tell it to center regardless and it did not fix the issue.

**Comment by jackpot51** [comment]
Fixed if on x11

**Comment by jackpot51** [comment]
We will release with only X11 enabled. This will fix this issue for now
