### ISSUE TITLE
"Ubuntu Single Sign-on" displayed as an online account option

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#33]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.04
 
 **Issue**
"Ubuntu Single Sign-on" is displayed as an online account option.

In Pop!_OS we do not normally show this login option.

**Comment by mmstick** [comment]
I'm updating the package at the moment.

**Comment by mmstick** [comment]
`gnome-online-accounts` is updated for disco, as well as the `initramfs-tools` package.

**Comment by brs17** [comment]
Looks to be resolved! Good work @mmstick

**Comment by brs17** [comment]
I do notice that Ubuntu SSO is not in gnome-control-center but only gnome-initial-setup.

**Comment by mmstick** [comment]
Our GOA package in the PPA is being overridden, so there's a new version of GOA currently being built in Proposed

**Comment by brs17** [comment]
I see the changes now just running `apt update && apt upgrade`
