### ISSUE TITLE
New Screen to Choose Dark or Light Mode During Setup

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-initial-setup#44]
Screen shot of each w/ selector.

**Comment by mmstick** [comment]
Should we have a widget that's used by both GNOME Settings and Initial Setup?

**Comment by mmstick** [comment]
What application(s) would be good in screenshots for demonstrating the different theme variants?

**Comment by WatchMkr** [comment]
Chatted in-person. Decided to use the widget in GNOME settings and a toggle under screenshots in GNOME Initial Setup. 

We're going to use user menu screenshots to highlight the modes.

**Comment by mmstick** [comment]
Here's a possible functioning widget, with two placeholder screenshots

![Screenshot from 2019-10-01 14-18-28](https://user-images.githubusercontent.com/4143535/65997305-5a9bef80-e456-11e9-9f37-a31f54c6b85a.png)

**Comment by mmstick** [comment]
Alternatively, we could have a stack switcher with two buttons that toggles the active screenshot.

**Comment by WatchMkr** [comment]
I like this layout. I think it's better to show both - and if this is above Backgrounds there is some synchronicity to it. We'll see if it actually looks good all together ;-).

I think our images will be taller. Let's get a couple screenshots.

**Comment by brs17** [comment]
This feature has been implemented.
