### ISSUE TITLE
Appearance tab should probably be shown after Language options

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#47]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-theme-switcher

**Issue/Bug Description:**
Seeing as the Appearance tab has translatable text, I would think it would make sense to have the tab shown after language/keyboard options in GNOME Initial Setup.

**Comment by mmstick** [comment]
It should appear after language, [as that's how it's defined](https://github.com/pop-os/gnome-initial-setup/blob/master_eoan/gnome-initial-setup/gnome-initial-setup.c#L69:L73)

**Comment by jackpot51** [comment]
I believe @brs17 was talking about after the keyboard page

**Comment by mmstick** [comment]
Moved with https://github.com/pop-os/gnome-initial-setup/commit/b6490b524f922b07080793e1bb87701233fbec29
