### ISSUE TITLE
Appearance choice not applied to new user

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#48]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-theme-switcher

**Issue/Bug Description:**
After selecting "Dark" in gnome-initial-setup, the user created started up in "Light" mode.

**Comment by mmstick** [comment]
At the end of initial setup, it executes the 'copy-worker', [which copies the dconf directory to the newly-created user's home folder](https://github.com/pop-os/gnome-initial-setup/blob/master/gnome-initial-setup/gnome-initial-setup-copy-worker.c#L92), so it should be using the GTK theme that's been defined there, unless the copy worker failed to run, or something overrode the GTK theme on login.

**Comment by jackpot51** [comment]
@mmstick that should be happening. I am looking into this now

**Comment by jackpot51** [comment]
Ok, I have an idea why this isn't working. The session needs to be set to `pop` as the gtk-theme is set for the `pop` session specifically

**Comment by jackpot51** [comment]
```
Exec=env GNOME_SHELL_SESSION_MODE=pop /usr/bin/gnome-session --systemd --session=pop
```

**Comment by jackpot51** [comment]
This does not appear to be fixed

**Comment by jackpot51** [comment]
This could potentially be fixed by calling https://gtk-rs.org/docs/gio/struct.Settings.html#method.sync when setting gtk theme

**Comment by jackpot51** [comment]
I think this is fixed in https://github.com/pop-os/theme-switcher/commit/73b29e88e3bdec0a8b91b61ed77141f649f64c08 which brought in https://github.com/pop-os/gtk-extras/commit/c55eb63bd92126206bd6ded2708a7cd869688822

We can try on Monday

**Comment by jackpot51** [comment]
This did not work :(
