### ISSUE TITLE
Ocassionally theme is not applied to user

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#49]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10 
 
**Issue/Bug Description:**
Seen dark theme not be set after gnome-initial-setup.

Related logs:
```
Oct 17 14:14:04 pop-os gnome-initial-s[1942]: Unable to move /run/gnome-initial-setup/.config/dconf/user to /home/system76/.config/dconf/user: Error moving file /run/gnome-initial-setup/.con
Oct 17 14:14:04 pop-os gnome-initial-s[1942]: Unable to move /run/gnome-initial-setup/.local/share/keyrings/login.keyring to /home/system76/.local/share/keyrings/login.keyring: Error moving 
```

Potentially by removing this file that is having issues before the attempt to copy, would solve the issue.

**Comment by mmstick** [comment]
This is because the file already exists at the destination?

**Comment by jackpot51** [comment]
Probably fixed by https://github.com/pop-os/gnome-initial-setup/commit/d484619ee3565341582e0fffabb3b641352d7494
