### ISSUE TITLE
Create user with 'lpadmin' group membership

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/gnome-initial-setup#54]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04 -- 19.10 
 
**Issue/Bug Description:**
Any changes to printer configuration requires authorization that fails unless user is created with 'lpadmin' group membership.

**Steps to reproduce (if you know):**
Install Pop!_OS, try and make a change the current settings for any automatically added printer.

**Expected behavior:**
Verify password and changes to printer is done.

**Other Notes:**
Currently the fix is to add your user to the lpadmin group:
sudo usermod -aG lpadmin $USER

You need to logout and login again, or restart the system.

**Comment by jacobgkau** [comment]
This is not done by GNOME Initial Setup, but it will now be done in AccountsService (which both GNOME Initial Setup and GNOME Control Center use when creating a new user): https://github.com/pop-os/accountsservice/pull/2 

The change will take effect for GCC when that update is released from proposed, and will take effect in GIS next time new .iso files and images are created after that.
