### ISSUE TITLE
Update screenshot on switchable graphics page to match GNOME 3.36

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-initial-setup#55]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
GNOME 3.36

**Issue/Bug Description:**
On the switchable graphics page of gnome-initial-setup, the screenshot should be updated to reflect changes in GNOME for 3.36.

![gis](https://user-images.githubusercontent.com/7460774/77201289-dc89de80-6ab1-11ea-9fee-2de2efb07ed8.png)
Note: The icons at the bottom of the system menu have been replaced in 20.04.

`master_eoan` will need to be created so that this change does not overwrite gnome-initial-setup on 19.10.

**Comment by WatchMkr** [comment]
Use a dark mode screenshot.
