### ISSUE TITLE
20.04: Welcome screen seems to have changed

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-initial-setup#57]
Previously the first page in  GIS showed the "P!" logo centered, with the scrolling languages beneath it. Now the logo is 4 squares, and it is no longer centered.
![IMG_20200408_111633](https://user-images.githubusercontent.com/13512097/78826909-8c5eb780-799f-11ea-9595-a0d78da04787.jpg)

**Comment by jackpot51** [comment]
Fixed by https://github.com/pop-os/gnome-initial-setup/commit/024e0bba1ba1c020b841bec6ccea32e1b87676dc
